# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1

orbs:
  node: circleci/node@3.0.0

jobs:
  middleTier:
    machine: true
		working_directory: ~/repo
    steps:
      # Docker is preinstalled, along with docker-compose
      - checkout
				path: ~/repo
      # start proprietary DB using private Docker image
      - run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker pull store/marklogicdb/marklogic-server:10.0-4-dev-centos
          docker run -d --privileged -p 0.0.0.0:7997-8002:7997-8002 -p 0.0.0.0:8010-8015:8010-8015 store/marklogicdb/marklogic-server:10.0-4-dev-centos
          ./.travis/setup-marklogic.sh
          ./.travis/run-tests.sh
  ui:
    working_directory: ~/repo/ui
    executor: node/default
    steps:
      - checkout
				path: ~/repo
      - node/install-packages
			-
      - run: npm run test:e2e:headless:ci

workflows:
  build_and_test:
    jobs:
      - middleTier
      - ui
